# Generated by Django 6.1.1 on 2026-09-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counters", "0001_initial"),
        ("events", "0001_initial"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="token",
            constraint=models.UniqueConstraint(
                fields=("event", "number"), name="unique_token_number_per_event"
            ),
        ),
    ]
